

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/NoticeBoard
    userName: henry
    password: zhtanf5246150!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: false
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
